export const REQUEST_PODCASTS = 'REQUEST_PODCASTS'
export const RECEIVE_PODCASTS = 'RECEIVE_PODCASTS'
export const SELECT_PODCASTS_PAGE = 'SELECT_PODCASTS_PAGE'
export const SET_PODCASTS_SEARCH = 'SET_PODCASTS_SEARCH'
